name: Build Document
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Compile English paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper-en.tex
      - name: Compile Indonesian paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper-id.tex
      - name: Save result
        uses: actions/upload-artifact@v2.2.3
        with:
          name: document
          path: |
            paper-en.pdf
            paper-id.pdf
